{{ if eq .Values.scope "cluster" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: skupper-operator
    application: skupper-controller
  name: skupper-controller
  namespace: skupper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application: skupper-controller
  name: skupper-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/exec
  - services
  - secrets
  - serviceaccounts
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - tlsroutes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - skupper.io
  resources:
  - sites
  - sites/status
  - links
  - links/status
  - accesstokens
  - accesstokens/status
  - accessgrants
  - accessgrants/status
  - listeners
  - listeners/status
  - connectors
  - connectors/status
  - attachedconnectors
  - attachedconnectors/status
  - attachedconnectorbindings
  - attachedconnectorbindings/status
  - routeraccesses
  - routeraccesses/status
  - securedaccesses
  - securedaccesses/status
  - certificates
  - certificates/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    application: skupper-controller
  name: skupper-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skupper-controller
subjects:
- kind: ServiceAccount
  name: skupper-controller
  namespace: skupper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-controller
  namespace: skupper
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skupper-controller
        app.kubernetes.io/part-of: skupper
        application: skupper-controller
        skupper.io/component: controller
    spec:
      containers:
      - args:
        - -enable-grants
        - -grant-server-autoconfigure
        command:
        - /app/controller
        env:
        - name: SKUPPER_KUBE_ADAPTOR_IMAGE
          value: quay.io/skupper/kube-adaptor:v2-dev
        - name: SKUPPER_KUBE_ADAPTOR_IMAGE_PULL_POLICY
          value: Always
        - name: SKUPPER_ROUTER_IMAGE
          value: {{ .Values.routerImage }}
        - name: SKUPPER_ROUTER_IMAGE_PULL_POLICY
          value: Always
        image: {{ .Values.controllerImage }}
        imagePullPolicy: Always
        name: controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /etc/controller
          name: tls-credentials
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: skupper-controller
      volumes:
      - emptyDir: {}
        name: tls-credentials
{{ end }}
